/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-electrosense
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#ifndef INCLUDED_ELECTROSENSE_API_H
#define INCLUDED_ELECTROSENSE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_electrosense_EXPORTS
#define ELECTROSENSE_API __GR_ATTR_EXPORT
#else
#define ELECTROSENSE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_ELECTROSENSE_API_H */
